version: '3'

services:
  postgres:
    container_name: guitartracks_db
    image: postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: guitartracks_test
    volumes:
        - db_data:/var/lib/postgresql/data
    ports:
        - "5432:5432"

  web:
    build: .
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - postgres

volumes:
  db_data:
