# Generated by Django 5.1 on 2024-08-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
